import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Link from 'next/link'

export default function Contact() {
    return (
        <div className={styles.container}>
      <Head>
        <title>Alec Nazworth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <h1 className={styles.title}>Contact</h1>

        <div className={styles.contacts}>
            <h2 className={styles.contact}>
                <Link href="https://github.com/alecnazzy">GitHub</Link>
            </h2>
            <h2>
                <Link href="https://www.linkedin.com/in/alec-nazworth-3ab6b4237/">LinkedIn</Link>
            </h2>      
            <h2>
                <Link href="https://www.instagram.com/alec.nazworth">Insta</Link>
            </h2>   
            <h2>
                <Link href="mailto:alecnazworthalt@gmail.com">Gmail</Link>
            </h2>
        </div>

        
        </main>
        <Footer />
    </div>
        
    )
}