import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alec Nazworth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <h1 className={styles.title}>
          <code>var myName: string = "Alec";</code>
        </h1>

        <p className={styles.description}>
          I'm a computer science student at Florida International University
        </p>

        <h1 className={styles.title}> Skills: </h1>
        <div className={styles.logos}>
          <Image className={styles.logo}
            src="/javascript-logo.png"
            alt="JavaScript Logo"
            width={50}
            height={50}
          />
          <Image className={styles.logo}
            src="/React-icon.svg.png"
            alt="React Logo"
            width={50}
            height={50}
          />
          <Image className={styles.logo}
            src="/nextjs-logo.png"
            alt="Next.js Logo"
            width={50}
            height={50}
          />
          <Image className={styles.logo}
            src="/nodejs-logo.png"
            alt="Node.js Logo"
            width={50}
            height={50}
          />
          <Image className={styles.logo}
            src="/java-logo.png"
            alt="Java Logo"
            width={50}
            height={50}
          />
          <Image className={styles.logo}
            src="/spring-logo.png"
            alt="Spring Logo"
            width={50}
            height={50}
          />
        </div>
      </main>
      <Footer />
    </div>
  )
}
