import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Link from 'next/link'
import Carousel from 'better-react-carousel'

export default function Projects() {
    return (
    <div className={styles.container}>
      <Head>
        <title>Alec Nazworth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main className={styles.main}>
        <Navbar />
            <h1 className={styles.title}>Projects</h1>
            <div className={styles.text}>
              <h1>Boba theme for VSCode</h1>
              <p>A little theme I cooked up after trying a hundred different 
                themes and my ocd rejecting all of them</p>
                <h3>
                <Link href="https://github.com/alecnazzy/boba-theme">
                  GitHub repository
                </Link>
              </h3>
              <div className={styles.carousel}>
              <Carousel cols={1} rows={1} gap={10} loop>
                <Carousel.Item>
                  <img width="100%" src="/html-boba.png" alt="" srcset="" />
                </Carousel.Item>
                <Carousel.Item>
                  <img width="100%" src="/js-boba.png" alt="" />
                </Carousel.Item>
                <Carousel.Item>
                  <img width="100%" src="/ts-boba.png" alt="" />
                </Carousel.Item>
                <Carousel.Item>
                  <img width="100%" src="/css-boba.png" alt="" />
                </Carousel.Item>
              </Carousel>
              </div>
              
              
            
            </div>
            
    
            <div className={styles.text}>
              <h1>Personal website</h1>
              <p>This is the website you are currently on. I made it with TypeScript, React, and Next.js</p>
              <h3>
              <Link href="https://github.com/alecnazzy/portfolio">
                  GitHub repository
                </Link>
              </h3>
            </div>  

        </main>
        <Footer />
    </div>

    
    )
}