import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Link from 'next/link'
import Carousel from 'better-react-carousel'

export default function Projects() {
    return (
    <div className={styles.container}>
      <Head>
        <title>Alec Nazworth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main className={styles.main}>

        <Navbar />

            {/* Title */}

            <h1 className={styles.title}>Projects</h1>

            {/* Boba theme project */}
            <div className={styles.text}>
              <h1>Boba theme for VSCode</h1>
              <p>A little theme I cooked up, inspired by the pastel colors common with
                 boba(bubble) tea that are easier for the eyes to digest.</p>
                <h3>
                <Link href="https://github.com/alecnazzy/boba-theme" target="_blank">
                  GitHub repository
                </Link>
              </h3>
              <div className={styles.carousel}>
              <Carousel cols={1} rows={1} gap={10} loop>
                <Carousel.Item>
                  <Image
                    src={"/html-boba.png"}
                    alt="HTML example"
                    width={700}
                    height={500}
                  />
                </Carousel.Item>
                <Carousel.Item>
                  <Image
                    src={"/js-boba.png"}
                    alt="JS example"
                    width={700}
                    height={500}
                  />
                </Carousel.Item>
                <Carousel.Item>
                  <Image
                    src={"/ts-boba.png"}
                    alt="TS example"
                    width={700}
                    height={500}
                  />
                </Carousel.Item>
                <Carousel.Item>
                  <Image
                    src={"/css-boba.png"}
                    alt="CSS example"
                    width={700}
                    height={500}
                  />
                </Carousel.Item>
              </Carousel>
              </div>
            </div>
            
          {/* Website portfolio project */}

            <div className={styles.text}>
              <h1>This Website</h1>
              <p>I created this site with TypeScript, React, Next.js, and deployed
                to the web using Vercel.</p>
              <h3>
              <Link href="https://github.com/alecnazzy/portfolio" target="_blank">
                  GitHub repository
                </Link>
              </h3>
              <div className={styles.carousel}>
              <Carousel cols={1} rows={1} gap={10} loop>
                <Carousel.Item>
                  <Image
                    src={"/home-screen.png"}
                    alt="Home screen"
                    width={700}
                    height={500}
                  />
                </Carousel.Item>
                <Carousel.Item>
                  <Image
                    src={"/project-screen.png"}
                    alt="Project screen"
                    width={700}
                    height={500}
                  />
                </Carousel.Item>
              </Carousel>
              </div>
            </div>  

        </main>

        <Footer />

    </div>
    )
}